services:
  selenium:
    image: selenium/standalone-chrome:117.0
    shm_size: "2g"
    ports:
      - "4444:4444"
    environment:
      SE_NODE_MAX_SESSIONS: "4"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4444/status || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 6
      start_period: 10s

  ui-tests:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - selenium
    environment:
      SELENIUM_URL: "http://selenium:4444"
    # Use $$SELENIUM_URL so Compose doesn't try to substitute it at compose-time;
    # the variable will be available inside the container at runtime.
    restart: "no"
