name: Contract Tests (ContractCukesRunner)

on:
  push:
    # update to x branch name as needed
    branches: [ x ]
#    branches: [ main, master, complete-ci-implementation ]
#  pull_request:
#    branches: [ main, master ]

permissions:
  contents: read

concurrency:
  group: contract-${{ github.ref }}
  cancel-in-progress: true

jobs:
  contract:
    name: Contract (ContractCukesRunner)
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Run Contract Cucumber tests
        id: test
        run: |
          set +e
          mvn -B -Dheadless=true -Dtest=ContractCukesRunner test
          code=$?
          echo "exitcode=$code" >> "$GITHUB_OUTPUT"
          exit 0

      - name: Rerun failed scenarios (if any)
        id: rerun
        if: ${{ steps.test.outputs.exitcode != '0' }}
        run: |
          if [ -f target/contract-rerun.txt ]; then
            cp target/contract-rerun.txt target/rerun.txt
            set +e
            mvn -B -Dheadless=true -Dtest=FailedTestRunner test
            code=$?
            echo "exitcode=$code" >> "$GITHUB_OUTPUT"
            exit 0
          else
            echo "No contract rerun file found"
            echo "exitcode=1" >> "$GITHUB_OUTPUT"
            exit 0
          fi

      - name: Upload Contract reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: contract-reports
          path: |
            target/contract-cucumber.json
            target/contract-cucumber-report.html
            target/allure-results/**
            target/contract-rerun.txt
            target/failed-html-report/**
          if-no-files-found: ignore
          retention-days: 14

      - name: Finalize job status
        if: always()
        run: |
          TEST_CODE='${{ steps.test.outputs.exitcode }}'
          RERUN_CODE='${{ steps.rerun.outputs.exitcode }}'
          if [ -z "$RERUN_CODE" ]; then RERUN_CODE=1; fi
          if [ "$TEST_CODE" != "0" ]; then
            if [ "$RERUN_CODE" != "0" ]; then
              echo "Contract tests failed and rerun did not succeed. Failing job." && exit 1
            fi
          fi

      - name: Cucumber Summary
        if: always()
        env:
          TEST_CODE: ${{ steps.test.outputs.exitcode }}
          RERUN_CODE: ${{ steps.rerun.outputs.exitcode }}
        run: |
          if [ -z "$RERUN_CODE" ]; then RERUN_CODE=1; fi
          if [ "$TEST_CODE" = "0" ]; then
            RESULT="success"; NOTE="(initial run)"
          elif [ "$RERUN_CODE" = "0" ]; then
            RESULT="success"; NOTE="(after rerun)"
          else
            RESULT="failure"; NOTE=""
          fi
          echo "# 🥒 Cucumber Summary - Contract" >> $GITHUB_STEP_SUMMARY
          echo "Result: ${RESULT} ${NOTE}" >> $GITHUB_STEP_SUMMARY
          echo "Artifacts: contract-reports" >> $GITHUB_STEP_SUMMARY
