name: Demo CI - E2E Checkout

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  demo-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Show Java version
        run: java -version

      - name: Run demo E2E scenario (headless Chrome)
        env:
          CI: true
        run: |
          # Ensure configuration file exists (uses template defaults in CI)
          if [ ! -f configuration.properties ]; then cp configuration.properties.template configuration.properties; fi
          ./mvnw -B -V -Dci.enforce=true -Dheadless=true -Dbrowser=chrome -Dcucumber.filter.tags="@demo" test

      - name: Archive reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: demo-reports
          path: |
            target/ui-api.json
            target/ui-api-report.html
            target/cucumber.json
            target/allure-results/**
            target/screenshots/**
