name: Nightly Performance Tests

on:
#  schedule:
    # Run every night at 2 AM UTC
#    - cron: '0 2 * * *'

  workflow_dispatch:
    inputs:
      notify_on_failure:
        description: 'Send notification on failure'
        required: false
        default: 'true'
        type: boolean

jobs:
  nightly-load-test:
    name: Nightly Load Test
    runs-on: ubuntu-latest

    # Add environment variables from secrets
    env:
      WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Install dependencies
        run: mvn clean install -DskipTests

      - name: Run Weather API Load Test
        run: |
          mvn gatling:test \
            -Dgatling.simulationClass=com.example.performance.simulations.WeatherApiPerformanceSimulation \
            -Dperf.users=20 \
            -Dperf.rampup=30 \
            -Dperf.duration=300 \
            -Dperf.type=load

      - name: Run E-commerce API Load Test
        run: |
          mvn gatling:test \
            -Dgatling.simulationClass=com.example.performance.simulations.EcommerceApiPerformanceSimulation \
            -Dperf.users=15 \
            -Dperf.rampup=20

      - name: Upload Nightly Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nightly-performance-reports-${{ github.run_number }}
          path: target/gatling-results/
          retention-days: 90

      - name: Extract Performance Metrics
        if: always()
        run: |
          mkdir -p performance-trends
          # Extract key metrics from Gatling logs
          if [ -d "target/gatling-results" ]; then
            for dir in target/gatling-results/*/; do
              if [ -f "${dir}js/stats.json" ]; then
                cp "${dir}js/stats.json" "performance-trends/stats-$(date +%Y%m%d).json"
              fi
            done
          fi

      - name: Upload Performance Trends
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: performance-trends-${{ github.run_number }}
          path: performance-trends/
          retention-days: 365

      - name: Performance Report Summary
        if: always()
        run: |
          echo "# 🌙 Nightly Performance Test Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Date:** $(date '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Tests Executed:**" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Weather API Load Test (20 users, 5 min)" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ E-commerce API Load Test (15 users)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Artifacts:**" >> $GITHUB_STEP_SUMMARY
          echo "- 📊 HTML Reports (90 days retention)" >> $GITHUB_STEP_SUMMARY
          echo "- 📈 Performance Trends (365 days retention)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Note:** Download artifacts to view detailed metrics and charts" >> $GITHUB_STEP_SUMMARY

      - name: Check for Performance Degradation
        if: always()
        run: |
          echo "Checking for performance regressions..."
          # Add custom logic here to compare with baseline
          echo "✓ Performance check completed"

      - name: Create Issue on Failure
        if: failure() && github.event.inputs.notify_on_failure != 'false'
        uses: actions/github-script@v7
        with:
          script: |
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '⚠️ Nightly Performance Test Failed',
              body: `## Performance Test Failure\n\n**Date:** ${new Date().toISOString()}\n**Run:** #${context.runNumber}\n\n**Action Required:**\n1. Review the [workflow run](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})\n2. Download and analyze the reports\n3. Investigate any performance degradation\n\n**Triggered by:** Scheduled nightly run`,
              labels: ['performance', 'automated-test', 'needs-investigation']
            });
            console.log('Created issue:', issue.data.number);
